/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourapp.Views;


import java.util.ArrayList;

import java.util.Date;

import javax.swing.ButtonGroup;

import javax.swing.JOptionPane;
import tourapp.Classes.AudioLanguage;
import tourapp.Classes.Booking;
import tourapp.Classes.BookingUtil;
import tourapp.Classes.CityTour;
import tourapp.Classes.SightseeingTour;
import tourapp.Classes.TourPackage;
import tourapp.Classes.Tourist;

/**
 *
 * @author user
 */
public class TourAppSystem extends javax.swing.JPanel {

    /**
     * Creates new form TourAppSystem
     */
     private ArrayList<Tourist> tourists;
     private ArrayList<TourPackage> tourPackages;
     private ArrayList<Booking> bookings;
     private ArrayList<AudioLanguage> audioLanguages;
     
    public TourAppSystem() {
        initComponents();
        /* Grouping of radio buttons city tour and sightseeing tour
        when a radio button is selected the other is deselected */
        ButtonGroup bgroupTourType = new ButtonGroup();
        bgroupTourType.add(sightseeingRadioButton);
        bgroupTourType.add(cityRadioButton);
        
        /* Grouping of radio buttons city tour and sightseeing tour
        when a radio button is selected the other is deselected */
        ButtonGroup bgroupWithGuide = new ButtonGroup();
        bgroupWithGuide.add(yesRadioButton);
        bgroupWithGuide.add(noRadioButton);
        
        //Created a Booking arraylist called bookings
        bookings = new ArrayList<Booking>();
        
        //Created an AudioLanguage arraylist called audioLanguages
        audioLanguages = new ArrayList<AudioLanguage>();
        for (AudioLanguage l: AudioLanguage.values())
        {
          audioLanguages.add(l);
        }
        
        //Created a Tourist arraylist called tourists
        tourists = new ArrayList<Tourist>();
        
        //Added new tourist(s) to tourists arraylist
        tourists.add(new Tourist("Oyinkansola","Nigeria",AudioLanguage.ENGLISH));
        tourists.add(new Tourist("Micheal","Senegal",AudioLanguage.FRENCH));
        tourists.add(new Tourist("Peter","Ghana",AudioLanguage.CHINESE));
        
        //Adding tourists to tourist list combo-box
        touristListbox.setSelectedItem(null);
        for(int i = 0; i < tourists.size(); i++)
        {
          touristListbox.addItem(tourists.get(i).toString());
        }
        
        //Created a TourPackage arraylist called tourPackages
        tourPackages = new ArrayList<>();
        tourPackages.add(new CityTour(true, 20,"city tour", "Nigeria", 85)) ;
	tourPackages.add(new SightseeingTour(24, "SightSeeingTour", "Ghana", 30));
        
        //Adding tourPackages to tour package list combo-box
        TPlistbox.setSelectedItem(null);
        for(int i = 0; i < tourPackages.size(); i++)
        {
          TPlistbox.addItem(tourPackages.get(i).toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        utilDateModel1 = new org.jdatepicker.impl.UtilDateModel();
        utilCalendarModel1 = new org.jdatepicker.impl.UtilCalendarModel();
        viewBIllbtn = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        button1 = new java.awt.Button();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        touristListbox = new javax.swing.JComboBox<>();
        TPlistbox = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 2), new java.awt.Dimension(2, 2), new java.awt.Dimension(2, 2));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        createBookingbtn = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        bookingslist = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cancelBookingbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        touristNameField = new javax.swing.JTextField();
        saveTouristbtn = new javax.swing.JButton();
        newTouristBookingbtn = new javax.swing.JButton();
        audioGuideBox = new javax.swing.JComboBox<>();
        touristCountryField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TPDescriptionLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        cityRadioButton = new javax.swing.JRadioButton();
        guideCostField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        sightseeingRadioButton = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        ticketCostField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        saveTPbtn = new javax.swing.JButton();
        newTPbtn = new javax.swing.JButton();
        TPDescriptionField = new javax.swing.JTextField();
        TPLocationField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TPCostField = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox1.setText("City Tour");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel9.setText("jLabel9");

        viewBIllbtn.setText("View Bill");

        label1.setText("label1");
        label1.getAccessibleContext().setAccessibleName("ViewBill");

        label2.setText("View Bill");

        button1.setLabel("button1");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Tourists");

        jLabel2.setText("Tour Packages");

        jLabel3.setText("Date and Time");

        touristListbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touristListboxActionPerformed(evt);
            }
        });

        TPlistbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPlistboxActionPerformed(evt);
            }
        });

        createBookingbtn.setText("Create Booking");
        createBookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBookingbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(touristListbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TPlistbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198)
                                .addComponent(createBookingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(touristListbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TPlistbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createBookingbtn))
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bookingslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingslistActionPerformed(evt);
            }
        });

        jLabel4.setText("Bookings");

        cancelBookingbtn.setText("Cancel Booking");
        cancelBookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelBookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingslist, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingslist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBookingbtn)
                .addGap(16, 16, 16))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Tourist");

        jLabel6.setText("Name");

        jLabel7.setText("Country");

        jLabel8.setText("Audio Guide Language");

        touristNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touristNameFieldActionPerformed(evt);
            }
        });

        saveTouristbtn.setText("Save Tourist");
        saveTouristbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTouristbtnActionPerformed(evt);
            }
        });

        newTouristBookingbtn.setText("New Tourist");
        newTouristBookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTouristBookingbtnActionPerformed(evt);
            }
        });

        jButton1.setText("View Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(touristCountryField)
                                    .addComponent(touristNameField))
                                .addGap(29, 29, 29)
                                .addComponent(saveTouristbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150))
                            .addComponent(audioGuideBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newTouristBookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newTouristBookingbtn)
                        .addComponent(jButton1)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(touristNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(touristCountryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveTouristbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(audioGuideBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Tour Package");

        TPDescriptionLabel.setText("Description");

        jLabel12.setText("Location");

        jLabel13.setText("Tour Cost");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("With guide");

        jLabel15.setText("Cost for the guide");

        yesRadioButton.setText("Yes");

        noRadioButton.setText("No");

        cityRadioButton.setText("City Tour");
        cityRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityRadioButtonActionPerformed(evt);
            }
        });

        jLabel19.setText("£");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cityRadioButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(guideCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yesRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(noRadioButton)
                                .addGap(23, 23, 23)))
                        .addGap(48, 48, 48))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cityRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(yesRadioButton)
                    .addComponent(noRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(guideCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(16, 16, 16))
        );

        jLabel19.getAccessibleContext().setAccessibleName("£");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sightseeingRadioButton.setText("Sightseeing Tour");

        jLabel17.setText("Cost for the tickets");

        jLabel18.setText("£");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sightseeingRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ticketCostField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sightseeingRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel18.getAccessibleContext().setAccessibleName("£");

        saveTPbtn.setText("Save Tour Package");
        saveTPbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTPbtnActionPerformed(evt);
            }
        });

        newTPbtn.setText("New Tour Package");
        newTPbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTPbtnActionPerformed(evt);
            }
        });

        jLabel16.setText("£");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(TPDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(TPCostField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addComponent(TPLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TPDescriptionField))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveTPbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newTPbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TPDescriptionLabel)
                            .addComponent(TPDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(TPLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TPCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(3, 3, 3))))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(newTPbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveTPbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        jLabel16.getAccessibleContext().setAccessibleName("£");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void TPlistboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPlistboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPlistboxActionPerformed

    private void touristListboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touristListboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_touristListboxActionPerformed

    private void createBookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBookingbtnActionPerformed
        // TODO add your handling code here:
        //Create a new booking for a tourist(s)
        
        Tourist tourist;
        TourPackage tourPackage;
        Date date = jDateChooser1.getDate();
        
        //Select a tourist
        int touristSelectedIndex =  touristListbox.getSelectedIndex();
        tourist = tourists.get(touristSelectedIndex);
        
        //Select a tour package
        int tourPackageSelectedIndex =  TPlistbox.getSelectedIndex();
        tourPackage = tourPackages.get(tourPackageSelectedIndex);
         
        //Error messages for not selecting either a tourist or a tour package or not putting date
        if(tourist == null)
        {
            JOptionPane.showMessageDialog(null, "Please Select a Tourist","warning",2);
        }
        
        if(tourPackage == null)
        {
           JOptionPane.showMessageDialog(null, "Please Select a Tour Package","warning",2);
        }
        
        if(date == null)
        {
           JOptionPane.showMessageDialog(null, "Please Select a date","warning",2);
        }
        
        //add booking to booking list combo-box
        Booking newBooking = new Booking(tourist, tourPackage, date);
        bookings.add(newBooking);
        bookingslist.addItem(newBooking.toString());
    }//GEN-LAST:event_createBookingbtnActionPerformed

    private void bookingslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingslistActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
                
         //Creates booking and add to booking list combo-box
        int selectedBookingIndex =  bookingslist.getSelectedIndex();
        Booking booking = bookings.get(selectedBookingIndex);
        
        touristNameField.setText(booking.getTourist().getName());
        touristCountryField.setText(booking.getTourist().getCountry());
        audioGuideBox.removeAllItems();
        audioGuideBox.addItem(booking.getTourist().getAudioLanguage().toString());
        
        TPDescriptionField.setText(booking.getTourPackage().getDescription());
        TPLocationField.setText(booking.getTourPackage().getLocation());
        TPCostField.setText(String.valueOf(booking.getTourPackage().getTourCost()));
    }//GEN-LAST:event_bookingslistActionPerformed

    private void touristNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touristNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_touristNameFieldActionPerformed

    private void newTouristBookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTouristBookingbtnActionPerformed
        // TODO add your handling code here:
        
        /*New Tourist botton after clicking should
        clear all tourist fields*/
        touristNameField.setText("");
        touristCountryField.setText("");
        
        audioGuideBox.removeAllItems();
      
      for (AudioLanguage l: audioLanguages)
        {
          audioGuideBox.addItem(l.toString());
        }
    }//GEN-LAST:event_newTouristBookingbtnActionPerformed

    private void newTPbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTPbtnActionPerformed
        // TODO add your handling code here:
        
        /*New Tour package after clicking should
        clear all tour package fields*/
        TPDescriptionField.setText("");
        TPLocationField.setText("");
        TPCostField.setText("");
        
        
    }//GEN-LAST:event_newTPbtnActionPerformed

    private void cancelBookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingbtnActionPerformed
        // TODO add your handling code here:
        
        // Cancel a booking and clear booking from booking list combo-box
        int selectedBookingIndex =  bookingslist.getSelectedIndex();

         if(selectedBookingIndex>1)
        bookings.remove(bookingslist.getSelectedItem());
        bookingslist.removeItem(bookingslist.getSelectedItem());
    }//GEN-LAST:event_cancelBookingbtnActionPerformed

    private void saveTouristbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTouristbtnActionPerformed
        // TODO add your handling code here:
        
        //Save new Tourist
        String name= "";
        String country= "";
        int selectedAudioIndex =  audioGuideBox.getSelectedIndex();
        
        //Error messages for skipping any input field
         if(!touristNameField.getText().isEmpty() || !touristNameField.getText().isBlank())
        {
            name = touristNameField.getText();
        }
         else{
             JOptionPane.showMessageDialog(null, "Please fill Tourist Name", "warning",2);
         }
        
        if(!touristCountryField.getText().isEmpty() || !touristCountryField.getText().isBlank())
        {
           country = touristCountryField.getText();
        }
        else{
            JOptionPane.showMessageDialog(null, "Please fill Tourist Nationality ","warning",2);
        }
        
        //add new tourist to tourist list combo-box
        audioGuideBox.getItemAt(selectedAudioIndex);
        audioLanguages.add(selectedAudioIndex, AudioLanguage.ENGLISH);
        Tourist tourist = new Tourist(name, country, audioLanguages.get(selectedAudioIndex));
        tourists.add(tourist);
        touristListbox.addItem(tourist.toString());
        
    }//GEN-LAST:event_saveTouristbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        /*View Bill button to return a string containing 
        total bill and total discounted bill*/
        int touristSelectedIndex =  touristListbox.getSelectedIndex();
        Tourist tourist = tourists.get(touristSelectedIndex);
        
        ArrayList<Booking> touristBookings = new ArrayList<Booking>();
        for (Booking b: bookings)
        {
         if(b.getTourist() == tourist)
         {
          touristBookings.add(b);
         }
        }
        
        BookingUtil util = new BookingUtil();
        double[] costAndDiscountedPrice = new double[2];
        
        costAndDiscountedPrice = util.calculateBill(bookings, tourist);
        
        JOptionPane.showMessageDialog(null, tourist.getName() +"'s bill is "+costAndDiscountedPrice[0]+ " and after discounts it is " +
                costAndDiscountedPrice[1]);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveTPbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTPbtnActionPerformed
        // TODO add your handling code here:
        
        //Save new tour package
        String location= "";
       
        if(!TPLocationField.getText().isEmpty() || !TPLocationField.getText().isBlank())
        {
           location = TPLocationField.getText();
        }
        else{
            JOptionPane.showMessageDialog(null, "Please fill Tour Package location field","warning",2);
        }
        
        double tourPackageCost = 0;
        if(!TPCostField.getText().isBlank() || !TPCostField.getText().isBlank()){
            tourPackageCost = Double.parseDouble(TPCostField.getText());
        }
        
        ArrayList<TourPackage> tourPackages = new ArrayList<TourPackage>(); 
        
        //radio button selection for new tour package
        
        //city tour RadioButton is selected
        if (cityRadioButton.isSelected()){
             if(!guideCostField.getText().isBlank() || !guideCostField.getText().isBlank()){
                 double guideCost = Double.parseDouble(guideCostField.getText());
                 
            boolean withGuide = false;
            if(yesRadioButton.isSelected()){
                withGuide = true;
            
                //select if withGuide is true
                TPDescriptionField.setText("City Tour");
                CityTour cityTour = new CityTour(withGuide, guideCost, "city tour", location, tourPackageCost);
                tourPackages.add(cityTour);
                TPlistbox.addItem(cityTour.toString());
            }
            
                
            else if(noRadioButton.isSelected()){   
                //select if withGuide is false
                TPDescriptionField.setText("City Tour");
                CityTour cityTour = new CityTour(withGuide, guideCost, "city tour", location, tourPackageCost);
                tourPackages.add(cityTour);
                TPlistbox.addItem(cityTour.toString());
            }
            else{
                JOptionPane.showMessageDialog(null, "Please select if with guide or not","warning",2);
                }
            
                }
            }
          
        //sightseeing RadioButton is selected
        else if (sightseeingRadioButton.isSelected()){
            
            if(!ticketCostField.getText().isBlank() || !ticketCostField.getText().isBlank()){
            double ticketCost = Double.parseDouble(ticketCostField.getText());
            
            TPDescriptionField.setText("Sightseeing Tour"); 
            SightseeingTour sightseeingTour = new SightseeingTour(ticketCost, "Sightseeing tour", location, tourPackageCost);
            tourPackages.add(sightseeingTour);
            TPlistbox.addItem(sightseeingTour.toString());
            }
            
            
        }
        //Error message if no tour package is selected
        else{
                JOptionPane.showMessageDialog(null, "Please select a tour package","warning",2);
            }
    }//GEN-LAST:event_saveTPbtnActionPerformed

    private void cityRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TPCostField;
    private javax.swing.JTextField TPDescriptionField;
    private javax.swing.JLabel TPDescriptionLabel;
    private javax.swing.JTextField TPLocationField;
    private javax.swing.JComboBox<String> TPlistbox;
    private javax.swing.JComboBox<String> audioGuideBox;
    private javax.swing.JComboBox<String> bookingslist;
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBookingbtn;
    private javax.swing.JRadioButton cityRadioButton;
    private javax.swing.JButton createBookingbtn;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JTextField guideCostField;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JButton newTPbtn;
    private javax.swing.JButton newTouristBookingbtn;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JButton saveTPbtn;
    private javax.swing.JButton saveTouristbtn;
    private javax.swing.JRadioButton sightseeingRadioButton;
    private javax.swing.JTextField ticketCostField;
    private javax.swing.JTextField touristCountryField;
    private javax.swing.JComboBox<String> touristListbox;
    private javax.swing.JTextField touristNameField;
    private org.jdatepicker.impl.UtilCalendarModel utilCalendarModel1;
    private org.jdatepicker.impl.UtilDateModel utilDateModel1;
    private javax.swing.JButton viewBIllbtn;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables
}
